Week1
pesto-students/p9-rahul-hitman-11 pull request #3
Opened 2023-01-22 11:52 UTC by hitman-11

Week 1 Assignment HTML Page

2023-01-29 05:54 UTC, rahul-pesto commented on Week-1/index.html
> +
code should be formatted before raising the PR

improper indentation in both HTML and CSS file

2023-01-29 05:54 UTC, rahul-pesto commented on Week-1/.readme
> +
why is this file empty?

2023-01-29 05:56 UTC, rahul-pesto requested changes
Assignment not completed!

please complete both parts of the assignment
Exercise 1: Create a readme file that explains browser functionality.
Exercise 2: Clone of mock-up which was provided, done in the HTML and CSS files.

2023-02-04 11:05 UTC, hitman-11 commented
Changes Made according to your PR comments. The new page looks like this.
![Screenshot (1)](https://user-images.githubusercontent.com/60355719/216763844-443c7c1b-5c22-461d-abd5-67b064eaf567.png)

2023-02-11 05:59 UTC, rahul-pesto approved these changes

2023-02-11 06:00 UTC, merged